name: oblt-google-auth
description: Grant pipelines access to Google Cloud resources using Workload Identity Federation
author: https://github.com/elastic
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    lifetime:
      type: number
    project-id:
      type: string
    project-number:
      type: number
    workload-identity-pool-suffix:
      type: string
      pattern: "^[a-z0-9]([a-z0-9-]{0,20}[a-z0-9])?$"
  additionalProperties: false
