env:
  GOOGLE_PROJECT: "elastic-observability-ci"

agents:
      provider: gcp
      image: family/core-ubuntu-2204
      machineType: 'n1-standard-1'
      preemptible: true

steps:
  - label: ":test_tube: Unit Tests"
    command: make test

  - label: ":gear: Integration Tests"
    command: make integration-test

  - label: ":lint-roller: Plugin Lint"
    command: make plugin-lint

  - label: ":shell: ShellCheck"
    command: make shellcheck

  - label: ":gcp: E2E - Test Plugin Functionality"
    plugins:
      - elastic/oblt-google-auth#${BUILDKITE_COMMIT}:
          lifetime: 10800
          project-id: "elastic-observability-ci"
          project-number: "911195782929"
    command: .buildkite/scripts/test-e2e.sh

notify:
  - slack: "#observability-ci"
    if: build.branch == "main" && build.state == "failed"
