name: BATS Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run BATS tests
        run: |
          make test
